### PR TITLE
Added pages to reset password

### PR DESCRIPTION
**Pull request by ruioliveira02**
Added two pages:

```forgot-password``` is the page the user clicks in order to request the email to reset the password
```password-recovery``` is the page the users receives a link to in the email

I wasn't sure what to say in the card, so suggestions are welcome.

### CODE REVIEW

**Comment by ruioliveira02** [comment]
image
image
image
image
image
image

**Review by feliciofilipe — APPROVED** [review]
Seems all good, I would ask you to wait for #165 to be merged and afterwards rebase.

#165 will change the Button component and you have to adapt its usage in the new pages you are creating.

**Comment by ruioliveira02** [comment]
Rebase done

**Review by feliciofilipe — APPROVED** [review]
:100:

**Review by mariajbp — APPROVED** [review]

**Pull request merged**
