### PR TITLE
fix: alignment issue of place under the award section

### LINKED ISSUE #511: Align "place" on awards listing
An example:
image

### PR DESCRIPTION
**Pull request by ShashwatPS**
Fixed the alignment issue of  place under the award section in the Challenges page.

 Fixes #511

### CODE REVIEW

**Comment by ShashwatPS** [comment]
Is there some issue with my code, do i need to fix anything ? @ruilopesm

**Comment by diogogmatos** [comment]
[fix: alignment issue of place under the award section](https://trello.com/c/W8gMrvZ0/55-fix-alignment-issue-of-place-under-the-award-section)

**Review by joaodiaslobo — CHANGES_REQUESTED** [review]
This works and makes it look exactly like we want, thank you! 🙇 
However, this project uses [Tailwind CSS](https://tailwindcss.com/), and we prefer to use it instead of normal CSS styling.
So, if you can, remove the `style` attributes and use the library's class names to syle items.

**Review by joaodiaslobo — APPROVED** [review]
Outstanding work, thank you! 🙇🚀

**Pull request merged**
