### PR TITLE
Update Informations

### PR DESCRIPTION
**Pull request by MarioRodrigues10**

### CODE REVIEW

**Review by ruioliveira02 — CHANGES_REQUESTED** [review]
- Schedule on the first date is not completely up to date
- Speakers are pretty much empty on day 1
- Please add the new team photos
- Remove the Join Our Staff 
- Add the login back

**Comment by MarioRodrigues10** [comment]
> * Schedule on the first date is not completely up to date
> * Speakers are pretty much empty on day 1
> * Please add the new team photos
> * Remove the Join Our Staff
> * Add the login back

Everything that you mentioned was already updated

**Review by ruioliveira02 — CHANGES_REQUESTED** [review]
image
image
Schedule is missing from main page

**Comment by MarioRodrigues10** [comment]
> image image Schedule is missing from main page

For some unknown reason Ricardo Rocha image if it stays like that will be correctly displayed in prod, you can find a similar example in ```deploy``` branch
Do you think we should have the schedule in main page? I think it's to much information and we have a proper page where the user can check the schedule.

**Review by ruioliveira02 — APPROVED** [review]

**Pull request merged**
