### PR TITLE
ref(Dashboard): New Layout global component to replace Dashboard comp…

### PR DESCRIPTION
**Pull request by EnzoVieira**
Since we have a lot of 'Dashboard' components, this new 'Layout' component should replace all of them in the future, becoming the pattern for all the pages.

I've made the refactor only for the Attendee pages, but the idea is to make this component as customizable as possible, so it can be used in other pages.

### CODE REVIEW

**Review by MarioRodrigues10 — CHANGES_REQUESTED** [review]
Could you please remove all the components named ```Dashboard``` in layout folder since we're using the same ```Dashboard``` component for every page now.

**Comment by EnzoVieira** [comment]
> Could you please remove all the components named `Dashboard` in layout folder since we will use the same `Dashboard` component for every page now.

Do you mean change all the `Dashboard` to `Layout`?

**Comment by MarioRodrigues10** [comment]
> > Could you please remove all the components named `Dashboard` in layout folder since we will use the same `Dashboard` component for every page now.
> 
> Do you mean change all the `Dashboard` to `Layout`?

So basically what i think is that we should remove every component named ```Dashboard``` inside ```Layout``` folder.
Check out ```layout/Attendee/components``` folder you will find a ```Dashboard``` inside that it isn't being used and so on in ```layout/Badge/components```, etc. 
Basically since they won't be used anymore just delete them.

**Review by MarioRodrigues10 — APPROVED** [review]
Good Job :+1:

**Pull request merged**
