### PR TITLE
Add auth logic flow

### PR DESCRIPTION
**Pull request by nelsonmestevao**

### CODE REVIEW

**Review by ruioliveira02 — APPROVED** [review]
There are some issues that will need to be solved. For example, there is no feedback in the login page for wrong credentials, and when switching pages an error related to the animation occurs.

However, the authentication works so I think it should be merged and I will fix these issues afterwards.

Again massive thank you for helping me with this, I really appreciate it :pray:

**Review by miguelbrandao — APPROVED** [review]
:rocket:

**Review by miguelbrandao — CHANGES_REQUESTED** [review]
The PR is good, but please ensure that Netlify checks pass

**Review by feliciofilipe — APPROVED** [review]

**Review by miguelbrandao — APPROVED** [review]
:rocket:

**Pull request merged**
