### PR TITLE
Update speakers design

### PR DESCRIPTION
**Pull request by feliciofilipe**

### CODE REVIEW

**Comment by mariajbp** [comment]
why?

**Comment by mariajbp** [comment]
It's not even user friendly you have to scroll back up to change the days

**Comment by feliciofilipe** [comment]
I dont get what are you asking. I only changed the color of the speakers on the home to gray like the figma design.

Check the files the **were** changed

**Comment by mariajbp** [comment]
Nvm, something is wrong on my screen will look into it and make a new issue.

**Review by nelsonmestevao — APPROVED** [review]
Great ◼️◻️

**Review by ruioliveira02 — APPROVED** [review]

**Pull request merged**
