### PR TITLE
refactor: remove back to sei website text from dashboard

### LINKED ISSUE #525: Remove "Back to SEI website" text
Remove the mentioned text and add the functionality to the below image.

### PR DESCRIPTION
**Pull request by maheshchandra10**
Fixes #525

### CODE REVIEW

**Comment by MarioRodrigues10** [comment]
Hi @maheshchandra10 , thanks for your contribution :raised_hands: 
This looks good, but could you please solve the conflits before I approve this.

**Comment by diogogmatos** [comment]
[Remove back to sei website text](https://trello.com/c/MEo4V8P0/10-remove-back-to-sei-website-text)

**Comment by maheshchandra10** [comment]
> Hi @maheshchandra10 , thanks for your contribution 🙌 This looks good, but could you please solve the conflits before I approve this.

Please check now maybe

**Comment by MarioRodrigues10** [comment]
Run `npm run format` in order to fix CI, and it's all good :raised_hands:

**Comment by maheshchandra10** [comment]
Not sure why the Code Quality check is failing. I took the latest code and ran npm run format and committed, still it fails.

**Comment by Darguima** [comment]
> Not sure why the Code Quality check is failing. I took the latest code and ran npm run format and committed, still it fails.

What's the output from the command?

I tried by my self and I could format and commit all the changes without problems.

**Comment by maheshchandra10** [comment]
> > Not sure why the Code Quality check is failing. I took the latest code and ran npm run format and committed, still it fails.
> 
> What's the output from the command `npm run format`?
> 
> I tried by my self and I could format and commit all the changes without problems.

It updated the files which were having formatting issues. I then just committed them and pushed. 
You can see the list of changed files in my latest commit.

**Review by ruilopesm — APPROVED** [review]
Thanks for your help, @maheshchandra10 🙌🏼

**Pull request merged**
