### PR TITLE
refactor: Staff Badge Component

### PR DESCRIPTION
**Pull request by Darguima**
I fixed the Badgedex on a previous PR, but now I noticed that also the "Give Badge" page from staff can use this component, so I adapted the Component to the staff and used it instead the repeated code.

The changes were that staff don't have badges so, we don't need highlight the owned ones, and that on the staff page we want a custom behavior instead that redirect to badge page.

Staff Page:
image

Attendee Page:
image

### CODE REVIEW

**Review by ruilopesm — COMMENTED** [review]
I don't know why, but I'm not able to list any badges as a staff. Probably not related with this PR, but can you do so?

**Comment by joaodiaslobo** [comment]
> I don't know why, but I'm not able to list any badges as a staff. Probably not related with this PR, but can you do so?

You can't list any badges as staff because the end time field for all badges has already passed the current date, re-running the seeds should fix the issue 🙏

**Comment by ruilopesm** [comment]
@joaodiaslobo Oh, you are totally right. Forgot about that constraint 😅

**Review by tiago-bacelar — APPROVED** [review]
I can't test the staff badges, but it seems legit :man_shrugging:

**Pull request merged**
