### PR TITLE
feat: Add hero typing animation

### PR DESCRIPTION
**Pull request by EnzoVieira**

### CODE REVIEW

**Review by joaodiaslobo — CHANGES_REQUESTED** [review]
The text isn't sizing correctly and I think the animation is a bit slow. Other than that awesome work! 💪 

image

**Review by tiago-bacelar — CHANGES_REQUESTED** [review]
Really cool! Though I think it would look even better with a terminal-like cursor instead of the default one.
Also, I noticed the animation plays every time the mobile navbar opens.
Adds #517

**Comment by EnzoVieira** [comment]
> Really cool! Though I think it would look even better with a terminal-like cursor instead of the default one. Also, I noticed the animation plays every time the mobile navbar opens.

Done ✅

But, the animation will run always when the parent component rerenders. Since the navbar is a parent component and it rerenders when click to open the menu, all it's child components will rerender, as the animation. I tried to save locally if the animation already ran but this causes another issue: 
_1. If the animation does not already ran: run it ✅ 
2. If the animation do already ran: the animation will not run again, so the text will no be shawn ❌_

So I could not fix this issue 😢. I don't think this will cause big UX/UI problems, this issue only appears if the user clicks to open menu multiple times, so we could keep it and try to refactor the Navbar in another PR.

**Review by tiago-bacelar — APPROVED** [review]
Seems good.
I do think the animation is a bit slow, though. I noticed you put it faster in your previous commit and then slowed it back down. Although it's cool on a first viewing, I feel like it could get boring on repeated viewings at the current speed. (We could always save on local cache whether the user already saw it multiple times :)

**Comment by EnzoVieira** [comment]
> Seems good. I do think the animation is a bit slow, though. I noticed you put it faster in your previous commit and then slowed it back down. Although it's cool on a first viewing, I feel like it could get boring on repeated viewings at the current speed. (We could always save on local cache whether the user already saw it multiple times :)

sorry 😅, it was my mistake change the animation duration again when I were debuggin yesterday. But I changed it back again!

**Comment by MarioRodrigues10** [comment]
I'm using firefox and these animation looks kinda fast, so could you slow it a little bit more?

**Comment by tiago-bacelar** [comment]
I'm on firefox too, I think the speed is fine. Maybe it could be slightly tweaked, but slowing it too much would make it boring and, honestly, I don't think it would be noticeably better.

**Review by tiago-bacelar — DISMISSED** [review]

**Review by MarioRodrigues10 — DISMISSED** [review]
Awesome job :star_struck:

**Review by tiago-bacelar — APPROVED** [review]

**Pull request merged**
