### PR TITLE
Responsive schedule

### PR DESCRIPTION
**Pull request by tiago-bacelar**
Made schedule component fully responsive
Last thing missing is setting the correspondence between the filters and the activity types (see Schedule/Table/index.jsx line 13)

### CODE REVIEW

**Review by feliciofilipe — APPROVED** [review]
:100::100::100:

**Review by ruioliveira02 — CHANGES_REQUESTED** [review]
image
Please center these components

**Comment by feliciofilipe** [comment]
@ruioliveira02 I think now the responsiveness is on point, let me know what do you think

**Review by feliciofilipe — DISMISSED** [review]
Approved

**Review by feliciofilipe — APPROVED** [review]
Approve

**Review by ruioliveira02 — APPROVED** [review]
Perfect

**Pull request merged**
